### ISSUE TITLE
How to set up with Tinty?

### ISSUE THREAD

**Issue by benjaminvdb** [tinted-theming/base16-gtk-flatcolor#6]
How do I set the colors up with Tinty? I have the following in my `config.toml`:

```toml
[[items]]
name = "base16-gtk-flatcolor"
path = "https://github.com/tinted-theming/base16-gtk-flatcolor"
themes-dir = "gtk-3"
hook = "cp -f %f ~/.themes/FlatColor/colors3"
supported-systems = ["base16"]
```

But it's not copying the file. I've tried setting a hook like `echo %f > ~/output.txt` to check whether the filename is correct but this file isn't being created either. It seems this repo is skipped but I don't understand why, since my other repos are working fine.

I hope I'm in the right place to ask this question. I wasn't sure to ask here or over at the tinty repo. Thanks!
